### ISSUE TITLE
Add swap in the VM

### ISSUE THREAD

**Issue by guillaumerose** [crc-org/snc#275]
**Change**

Add swap in the VM

**How**

Implemented in https://github.com/code-ready/snc/pull/246

**Expected and mesured improvements**

**Pros**

**Cons**

**Comment by guillaumerose** [comment]
Minkube has an option for swap but it's disabled by default.

**Comment by praveenkumar** [comment]
https://github.com/kubernetes/kubernetes/issues/53533 have more details around it.

**Comment by cfergeau** [comment]
This is moving forward in https://github.com/crc-org/snc/issues/861
