### ISSUE TITLE
New branch for microshift bundle creation

### ISSUE THREAD

**Issue by praveenkumar** [crc-org/snc#590]
microshift bundles are not able to created same way as podman or openshift bundles. It have some prerequisites and by default `snc.sh` script not work. This issue is to discuss what would be much cleaner approach to create a microshift bundle. Either by a branch or creating another script `microshift.sh` in master branch which start the microshift VM and then createdisk script able to create the bundle.

As of now the steps required.
- Clone the microshift repo https://github.com/openshift/microshift 
- Remove the customization of service and use `core` user
   - `sed -i '/# customizations/,$d' scripts/image-builder/config/blueprint_v0.0.1.toml` 
   -  `sed -i 's/redhat/core/g' scripts/image-builder/config/kickstart.ks.template`
- Create the rpm for offline images
  - https://github.com/openshift/microshift/blob/main/docs/rhel4edge_iso.md#offline-containers
- Create the rpm for microshift
  - `make rpm`
- Build Installer (ISO)
  - https://github.com/openshift/microshift/blob/main/docs/rhel4edge_iso.md#building-installer 
- Create VM using generated ISO
  - https://github.com/openshift/microshift/blob/main/docs/rhel4edge_iso.md#install-microshift-for-edge

Create disk image which need some changes in the script side.

**Comment by cfergeau** [comment]
In my opinion, the separate branch we have for podman is something we should be getting rid of. We already had bugs because needed commits were in one branch and not the other. So I'd avoid adding a new branch for microshift.

**Comment by gbraad** [comment]
> creating another script microshift.sh

prefered

**Comment by praveenkumar** [comment]
We already have now the way to create the microshift bundle using `microshift.sh` script.
