### ISSUE TITLE
Revert pull #600 once registry.redhat.io/container-native-virtualization/hostpath-csi-driver-rhel8 available for arm64

### ISSUE THREAD

**Issue by praveenkumar** [crc-org/snc#601]
This is the tracking issue to make sure we don't miss to revert the image change once it available downstream for arm64

- https://github.com/crc-org/snc/pull/600

**Comment by praveenkumar** [comment]
looks like it is now available registry.redhat.io/container-native-virtualization/hostpath-csi-driver-rhel9:v4.13 for arm64

**Comment by anjannath** [comment]
Running a test here https://github.com/crc-org/snc/pull/721

**Comment by praveenkumar** [comment]
fixed with #743
