### ISSUE TITLE
createdisk.sh fails on arm64 while trying to install qemu-ga selinux policy

### ISSUE THREAD

**Issue by anjannath** [crc-org/snc#622]
On the arm64 machine it fails with the following error, while on amd64 the error does not occur (not sure if the Selinux stuff can be affected by the cpu arch)
```
+ prepare_qemu_guest_agent api.crc.testing
+ local vm_ip=api.crc.testing
+ /usr/bin/checkmodule -M -m -o qemuga-vsock.mod qemuga-vsock.te
+ /usr/bin/semodule_package -o qemuga-vsock.pp -m qemuga-vsock.mod
+ scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i id_ecdsa_crc qemuga-vsock.pp core@api.crc.testing:
Warning: Permanently added 'api.crc.testing' (ED25519) to the list of known hosts.
qemuga-vsock.pp                                                                                                                                               100%  968     3.7MB/s   00:00    
+ ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i id_ecdsa_crc core@api.crc.testing 'sudo semodule -i qemuga-vsock.pp && rm qemuga-vsock.pp'
Warning: Permanently added 'api.crc.testing' (ED25519) to the list of known hosts.
libsemanage.semanage_pipe_data: Child process /usr/libexec/selinux/hll/pp failed with code: 255. (No such file or directory).
qemuga-vsock: libsepol.policydb_read: policydb module version 20 does not match my version range 4-19
qemuga-vsock: libsepol.sepol_module_package_read: invalid module in module package (at section 0)
qemuga-vsock: Failed to read policy package
libsemanage.semanage_direct_commit: Failed to compile hll files into cil files.
 (No such file or directory).
semodule:  Failed!
```
I tried copying the policy file inside the VM and build the module and package in the VM and after that it was able to install

**Comment by anjannath** [comment]
Although the installation of the module succeeded, the `qemu-guest-agent.service` is in failed state

**Comment by cfergeau** [comment]
Is this happening with podman or with openshift bundles?

> I tried copying the policy file inside the VM and build the module and package in the VM and after that it was able to install

Did you have to install additional packages for this?

> Although the installation of the module succeeded, the qemu-guest-agent.service is in failed state

Probably because the VM  does not have a vsock device, I have a patch for this for the podman branch, but not sure we'll solve it for openshift. crc adds the right device when timesync is enabled.

**Comment by praveenkumar** [comment]
This is now fixed, closing it.
