### ISSUE TITLE
Extend certification expiry on nightly builds 

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/snc#646]
Currently nightly code for OCP builds controls the certificate expiry with an `dev` parameter only allowing duration for X hours, so even when we wait for cert renewal during bundle build the new certificates only have validity for X hours.

It would be a big win to adapt the current feature we got for our released bundles with patched `KAO` and `KCMO` to be used within the nightly builds.

**Comment by praveenkumar** [comment]
Internal jenkins job is now enabled to create patched images for `ec/rc` and since there is no more nightly so only `ec` bits are good enough for this.

Closing this issue because it is now in place.
