### ISSUE TITLE
build hospath-csi-driver image in brew

### ISSUE THREAD

**Issue by anjannath** [crc-org/snc#650]
https://github.com/crc-org/snc/blob/4ada0a93e0e3de2b0fbd328ef43096c7563a7ed9/kubevirt-hostpath-provisioner-csi/csi-driver/kustomization.yaml#L5
currently the image building is not automated, this'd allow us to keep the image updated and support additional architectures

**Comment by cfergeau** [comment]
Filed an internal ticket to ask for this.

**Comment by praveenkumar** [comment]
we don't require this any more because image is available for amd64/arm64 for `hostpath-csi-driver`.
