### ISSUE TITLE
'developer' user doesn't have access to 'default' namespace

### ISSUE THREAD

**Issue by anjannath** [crc-org/snc#703]
it seems the `developer` user doesn't have sufficient permissions to list/access/modify resources in the `default` namespace, but is should be able to do it since we also add a kube context `crc-developer` that has the namespace set to `default`

```
❯ oc whoami
developer

❯ oc project
error: you do not have rights to view project "default" specified in your config or the project doesn't exist

❯ oc config get-contexts
CURRENT   NAME            CLUSTER                AUTHINFO    NAMESPACE
          crc-admin       api-crc-testing:6443   kubeadmin   default
*         crc-developer   api-crc-testing:6443   developer   default
```

**Comment by Apetree100122** [comment]
❯ oc  whoami developer ❯ oc project
error: you    do not have rights
 to view project "default"    specified in your    
config or the project    doesn't exist ❯ oc  config   
   get-contexts            ||   
|--CURRENT   NAME              "crc-admin"  |   "crc-developer "|
|| --- CLUSTER          "api-crc-testing:6443"   |   " api-crc-testing:6443 " |
| -- AUTHINFO                        "kubeadmin"    |    " developer"  |
|--|  NAMESPACE                           " default "     |     " default "  |
||

**Comment by Apetree100122** [comment]
you need to not be default as if you do your dev will not have access

**Comment by praveenkumar** [comment]
So the concern is because as part of context setting we use the default namespace, what if we don't use any namespace then user get following which I think is clear right?

```
$ oc config get-contexts
CURRENT   NAME            CLUSTER                AUTHINFO                         NAMESPACE
          crc-admin       api-crc-testing:6443   kubeadmin/api-crc-testing:6443   default
*         crc-developer   api-crc-testing:6443   developer/api-crc-testing:6443   

$ oc project
No project has been set. Pass a project name to make that the default.

$ oc project demo
error: You are not a member of project "demo".
You are not a member of any projects. You can request a project to be created with the 'new-project' command.
```
