### ISSUE TITLE
[Microshift] Running x86_64 arch container image in aarch64 bundle

### ISSUE THREAD

**Issue by praveenkumar** [crc-org/snc#710]
For M1 we provide aarch64 bundles which doesn't have `qemu-user-static` package installed and it is not even available for RHEL- 8/9 https://access.redhat.com/solutions/5654221 . But for podman preset FCOS have those packages and able run different image on different platform. There are lot of demos which is going to fail on microshift because of not able to run different arch image. What should be best approach

- Should we install `qemu-user-static` package from fedora since it is not part of EPEL also?
- Should we not do anything and tell user to update their workload image and create it for all the arch?

Some relative links:
- https://github.com/containers/podman/issues/15456
- https://github.com/crc-org/crc/issues/3483

**Comment by anjannath** [comment]
worth asking in the fedora community to add it to EPEL, (not sure how long it'll take) fedora docs page for requesting packages to be built in EPEL https://docs.fedoraproject.org/en-US/epel/epel-package-request/

**Comment by praveenkumar** [comment]
we are now using the `qemu-user-static` package from fedora which able to run x86_64 container image to M1.
