### ISSUE TITLE
kernel is downgraded for *all* bundles

### ISSUE THREAD

**Issue by cfergeau** [crc-org/snc#745]
https://github.com/crc-org/snc/commit/68c6383de78d658b2581fb0f5097dbf34618befc moved the kernel changes from an aarch64-only block to a block which is run when the macOS bundle is enabled. However, the kernel downgrade is done before any bundle is generated, so the kernel will be downgraded for all our bundles, linux, macos, windows.

We need to do something similar to https://github.com/crc-org/snc/pull/637 to address this.

**Comment by cfergeau** [comment]
> This does not seem to have been scheduled. Any idea about priority and/or sprint this will be dealt with?

Praveen has already been working on this in https://github.com/crc-org/snc/pull/749

**Comment by praveenkumar** [comment]
This is already taken care of.
