### ISSUE TITLE
[BUG] Failed updating pullsecret on candidate version 4.14.0.ec.4

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/snc#783]
Testing candidate version 4.14.0-ec.4 almost every `crc start` ends up failing due to timeout trying to update pullsecret to disk. 

This can be checked from [e2e results](https://crcqe-asia.s3.ap-south-1.amazonaws.com/nightly/ocp/4.14.0-ec.4/qe-results/e2e-non-ux.xml) and [logs](https://crcqe-asia.s3.ap-south-1.amazonaws.com/nightly/ocp/4.14.0-ec.4/qe-results/test-results/e2e_2023-8-4_22-22-44.log)

**Comment by praveenkumar** [comment]
closing it, transferred to snc side.

**Comment by praveenkumar** [comment]
We added the check for machine config, closing it now.
