### ISSUE TITLE
microshift: use GPT partition table

### ISSUE THREAD

**Issue by cfergeau** [crc-org/snc#801]
Microsoft Hyper-V "gen2" virtual machines require a GPT partition table for their disk images.
The openshift bundle we generate has such a partition table, but not the microshift bundle.
We most likely need to make some changes to microshift/scripts/image-builder/config/kickstart.ks.template to achieve this.

**Comment by gbraad** [comment]
^^^ Interesting, as I am testing with Microshift. Would be VERY helpful if this can be resolved.

**Comment by cfergeau** [comment]
This was fixed by https://github.com/crc-org/snc/pull/802
