### ISSUE TITLE
Missing  installation config for ImageRegistry capability on v4.14

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/snc#806]
On Openshift `v4.14` ImageRegistry has been added as [cluster capability](https://github.com/openshift/api/blob/7d89b46689d4eaca39e9875f9fa593ee3e06bd63/config/v1/types_cluster_version.go#L424-L437), with the current installation config it is not set as Enabled so it is not being installed. 

Running snc for `4.14.0-rc1` the cluster installation finishes successfully but after snc installs the hostpath provisioner and it tries to create a PVC for the image registry it fails as the `namespace` does not exist:

```
+ ./openshift-clients/linux/oc apply -f registry_pvc.yaml
Error from server (NotFound): error when creating "registry_pvc.yaml": namespaces "openshift-image-registry" not found
```

**Comment by cfergeau** [comment]
Closing this, the PR/commit was probably missing "Fixes #xxx" so that it's closed automatically :)
