### ISSUE TITLE
 Tracker issue for 4.15 readiness

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/snc#837]
- [x] https://github.com/crc-org/snc/issues/830
- [x] #838
- [ ] #850

**Comment by adrianriobo** [comment]
`4.15.0-rc4` qe [pass](https://crcqe-asia.s3.amazonaws.com/nightly/ocp/4.15.0-rc.4/qe-results/e2e-non-ux.xml)

**Comment by praveenkumar** [comment]
Bundle is generated and in testing phase.
