### ISSUE TITLE
[4.15.X] Invalid value: "OpenShiftSDN": networkType OpenShiftSDN is deprecated, please use OVNKubernetes

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/snc#850]
Testing `4.15.0-rc5` during bundle creation the cluster installation is failing due to an error with the install config value for the networking:

```bash
**+ ./openshift-baremetal-install --dir crc-tmp-install-data create manifests
level=error msg=failed to fetch Master Machines: failed to load asset "Install Config": failed to create install config: invalid "install-config.yaml" file: networking.networkType: Invalid value: "OpenShiftSDN": networkType OpenShiftSDN is deprecated, please use OVNKubernetes
```

**Comment by cfergeau** [comment]
This is documented in 4.14 release notes:

https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html-single/release_notes/index

>1.5.3. Notice of future deprecation
>1.5.3.1. Future deprecation of the OpenShift SDN network plugin
>
>It is currently planned that the OpenShift SDN CNI network plugin will not be an option for new installations in the next minor release of OpenShift Container Platform. However, at that time, it is planned to be supported in clusters that were previously installed with the OpenShift SDN network plugin. In a subsequent future release, the OpenShift SDN network plugin will be removed and no longer supported.

**Comment by praveenkumar** [comment]
We switched to OVN-K from SDN.
