### ISSUE TITLE
install LVMS operator for openshift preset

### ISSUE THREAD

**Issue by anjannath** [crc-org/snc#867]
By following the installation guide on: https://docs.openshift.com/container-platform/4.15/storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms.html#install-lvms-operator-cli_logical-volume-manager-storage

create the namespace, operatorgroup and subscription resources during snc leaving the `LVMCluster` crd resource to be created upon `crc start`

**Comment by praveenkumar** [comment]
I am thinking it again and following points what I observe

- Changes are what is part of the operator installation which also means we have to maintain it for different  OCP releases (major/minor) and if something change we have to update it (like we are doing for current hostpath operator).
- Since this is installed during snc does that mean any other image is pulled or it is just the crd installation and there is no change in bundle size and default resource if the user not consuming it?

**Comment by anjannath** [comment]
>     * Changes are what is part of the operator installation which also means we have to maintain it for different  OCP releases (major/minor) and if something change we have to update it (like we are doing for current hostpath operator).
>

for the hostpath-provisioner we have to maintain the versions of the images because its not installed as a operator, but we create daemonsets and some service plus rbac stuff, but the LVMS is a operator managed by OLM so for this we don't have to bump versions of the images, we just have to create the subscription and the correct version is installed by OLM.. 

the two resources that we are creating for this during SNC (operator-group and subscription) don't have any version related fields in the spec

>     * Since this is installed during snc does that mean any other image is pulled or it is just the crd installation and there is no change in bundle size and default resource if the user not consuming it?

yes images are pulled, there's an increase of ~100MB in bundle size, and it creates a deployment with 1 replica after the operator is installed

**Comment by praveenkumar** [comment]
> yes images are pulled, there's an increase of ~100MB in bundle size, and it creates a deployment with 1 replica after the operator is installed

In this case should we just copy those artifacts to VM under `/opt/crc/lvms` and then when user really want to consume that then only apply those to cluster? This way we don't have to increase the bundle size and extra deployment and the config will be also part of bundle?

**Comment by anjannath** [comment]
> > yes images are pulled, there's an increase of ~100MB in bundle size, and it creates a deployment with 1 replica after the operator is installed
> 
> In this case should we just copy those artifacts to VM under `/opt/crc/lvms` and then when user really want to consume that then only apply those to cluster? This way we don't have to increase the bundle size and extra deployment and the config will be also part of bundle?

this is done in snc to reduce the time the user has to wait for `crc start` to finish, if we install the operator during crc start it increases the start time by around ~2mins, i mentioned about the increase in start time also in https://github.com/crc-org/snc/issues/854#issuecomment-2009158945
