### ISSUE TITLE
Download/use the same podman as for the cluster on linux

### ISSUE THREAD

**Issue by cfergeau** [crc-org/snc#868]
This code https://github.com/crc-org/snc/blob/2a4aee82cf2eba7d0d1d51c634f15b72c1de8b44/createdisk-library.sh#L391 which was added in https://github.com/crc-org/snc/commit/f4d7855ff6cb452b9d8d4d3ee3bce8d27eaf7a51 is probably no longer needed.

**Comment by redbeam** [comment]
Merged
