### ISSUE TITLE
Use container image build metadata from brew to determine the image name

### ISSUE THREAD

**Issue by praveenkumar** [crc-org/snc#871]
This is the follow up issue from https://github.com/crc-org/snc/pull/831#discussion_r1512372832 one. As of now inplace image name is updated but in future when component is changed to `rhel10` then it again need updated so better to use jq on the image metadata for get the name.

```
$ curl -L -O https://download.eng.bos.redhat.com/brewroot/packages/crc-cluster-kube-apiserver-operator-container/${version}/${release}/metadata.json
$  jq .build.extra.image.index.pull metadata.json 
[
  "registry-proxy.engineering.redhat.com/rh-osbs/openshift-crc-cluster-kube-apiserver-rhel9-operator@sha256:d5706c6abf05f67c1c943b54d6d976887b95ad0b5514fb725b39df4ceb2b24c6",
  "registry-proxy.engineering.redhat.com/rh-osbs/openshift-crc-cluster-kube-apiserver-rhel9-operator:v4.15.0-202403071539.p0.g9fe0ab1.assembly.stream.el9"
]
```

from pull list we can choose any one because one is with sha256 digest and another one with the tag and both images are same.

**Comment by redbeam** [comment]
Merged
