### ISSUE TITLE
Readiness check for Openshift-4.16.x

### ISSUE THREAD

**Issue by praveenkumar** [crc-org/snc#881]
Since the rc bits are now available, this will be the tracker issu for 4.16 readiness till we publish the 4.16 bundle after it is released.  All the issues related to 4.16 should be added to this tracker issue.

- [x] #882 
- [x] #900 
- [x] #901
- [x] #904
- [x] #910
- [x] #922

**Comment by praveenkumar** [comment]
https://issues.redhat.com/browse/CRC-335 internal Jira

**Comment by adrianriobo** [comment]
OCP 4.16 has been released successfully within Openshift Local
