### ISSUE TITLE
Switch to UEFI for vfkit driver and remove kernel related file

### ISSUE THREAD

**Issue by praveenkumar** [crc-org/snc#897]
Discussion: https://github.com/crc-org/crc/issues/4180

We should also update the version info https://github.com/crc-org/snc/blob/ecb02eb8606b4c9e7468885c06a1b8652714b9fc/crc-bundle-info.json.sample#L11 to `1.5` once PR is filled.

**Comment by cfergeau** [comment]
This is done now.
