### ISSUE TITLE
Investigate failing pipeline for release 4.17

### ISSUE THREAD

**Issue by redbeam** [crc-org/snc#948]
The pipeline has been fixed for 4.16, but there is a problem with 4.17.

**Comment by redbeam** [comment]
It seems that additional monitor tests need to be disabled for 4.17.

**Comment by praveenkumar** [comment]
@redbeam go for it, if you think tha disabling that test make the CI green.

**Comment by redbeam** [comment]
The pipeline is passing after disabling additional tests.
